/**
 * Inline data URL of the bundled scientist PNG. Generated by base64
 * encoding `scientist.png` once (the PNG itself stays in this dir as
 * the source of truth — regenerate this constant via
 * `base64 -w 0 scientist.png` if the asset ever changes).
 *
 * Used by `BUILT_IN_SCIENTIST_SPRITESET.image.path` so the engine can
 * load the starter character without any file-resolution path. Works
 * identically across GJS (where `file://` paths require absolute
 * resolution) and the browser.
 */
export const SCIENTIST_PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUAAAAAgCAMAAABUzVF2AAAAAXNSR0IArs4c6QAAAEhQTFRFAAAA9raK9/f3bG23hYWF7+/vcDg40tLSAAAAPT09/////9Gt2opoqWcswMDRuLi4U1R2ODg4gjhHT09P0L9fgoKKPygo9vb2cHUMBAAAABh0Uk5TAP//////////////////////////////6dxENgAABDdJREFUaIHtltu2oyAMQLkJoWq107n8/59OAmglYGfSOfMm6xxXw+aSbNFWqatd7WpXu9rVrna1q13tah+2+D/4ly/6ZQt+fWYhvh0h5v9l0Tj8YcLf8i9b6JBrcDHGQxz/iSsMsI8Pip/z1MHyPtYh4nEIsSqnmSjjtDwawIS3vkaYlN9COISNECmPmHIIw6kwIY9DCl/pNsJkPPkIzr0UMCFSHsPtFsjBiVAhT+UP2GJfiJhjx0AO3FYOFybluf7kJOXMhEh5qp/abTPAhMh4SZ9SdrEjRM5LFLYdmRAxp7pzBQ56QsW81I+90BMm5uQjpIzJQCtEyEPCYTjUcxQi50lA/k87MiFiHvb6XegJEfKYUw9JA/SEyXjMn1LrCf2I3/ZL5EI+43hEsfxb2pELkfGkw5URAzRCPubBDaUAJkTIFWyrh6S4EfIJd3q8OY0WqAImRMyxfvyYahh6QmQ8C6DatcsnkgsT8qPBdCCYkE841j+6UU+uJ+Q9b+Zjwg4jytmlDVohQk7bkADs7QoVcgX52yAdg9ATIuZ+0qDxb/IdoWIe3Qijzl9b+RXHhch4SjjtCWNPqJSnEtJ3ak6/FfKOxw530U9Wazv5SD2+EVbzSpjvcK/tiAbQb+gJlXIswE2a7pnVviNUzHFLIAUOoPxSfAnJI2rux1pYMx+i8RM2byL504YLqzjuBlPmE37wDaclUMA3PcEW1kKkXAFMGGJfrr8RIuQqGgMP5x5gTPklSyEJMWkI4340WdijCOPzMV48tiXFXmsDWQiU300VTwYLN5o25DytgRzOhAg5CsE7Nemt/o4wESchaADr34TdDQmCu3n6HvdPc08DzD12OB45s5gF/4yhA4UmfmUhz2eupuZKPZ+GePLW41TC/Q5wJkzK6RPFG2yFibgffwAJwcuPLMhkH3fjuxwH3PMI4zscswesHS1A2RNgE7KoDl82YVBeWXy+olzopm0p04rLQViHV0IZBzocVENfSJcvyzs+z/PjgZc0xo/jT9rMbEsynvOhRX7mQ825x5gEYLy9M7IQnQ8U52isCCtPIJ+/CXhVQI/38hLWcCa04UwAE9LhtJ8/4wqspROEV5UFQhayH/mKY1yEQXkrNHxd5+/f53Xd4yxkP1A1R4GZryfzUQA+Fd7uCeNbA/3Zg7Cat0IZtxSfCmu5JYP7I9zhWHu6lOWACan5Lmx7Rjo8tz3OQrzvc+8zP5uv1OzxXs27T4yWebbrGbczFbjHnOMJSLE6xDR+349xWO08L9hzwlVWBYeE6al/hQ2njwBwNr/garxl4yue7lmzvK2OjGcRtvWUWyrwdL50PArE1mRwXA9e171rPeTHOLF6MOM8tsfduvux+8f4Ue9+P0453Q/v6xvAM7A1pfEAJzydp04K6n2DNwPesU/Hvx0D7IbxsW1P3dfwt/Avttij3wSZeXq+P4plAAAAAElFTkSuQmCC'
